<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="82" started-at="2017-10-24T05:37:17Z" finished-at="2017-10-24T05:37:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="82" started-at="2017-10-24T05:37:17Z" finished-at="2017-10-24T05:37:17Z">
      <class name="com.epam.ftm.demo1.HelloWorldTestNG">
        <test-method status="FAIL" signature="test1Failed()[pri:0, instance:com.epam.ftm.demo1.HelloWorldTestNG@5d5eef3d]" name="test1Failed" duration-ms="24" started-at="2017-10-24T08:37:17Z" finished-at="2017-10-24T08:37:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[No matching text is found. Please, try again. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: No matching text is found. Please, try again. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.epam.ftm.demo1.HelloWorldTestNG.test1Failed(HelloWorldTestNG.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1Failed -->
        <test-method status="PASS" signature="test2()[pri:0, instance:com.epam.ftm.demo1.HelloWorldTestNG@5d5eef3d]" name="test2" duration-ms="6" started-at="2017-10-24T08:37:17Z" finished-at="2017-10-24T08:37:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- com.epam.ftm.demo1.HelloWorldTestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
